name: report_excel
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  lottie: ^2.3.2
  flutter_animate:
  progress_state_button: ^1.0.4
  dropdown_button2:
  animated_text_kit: ^4.2.2
  
#dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: InterBlack
      fonts:
        - asset: assets/fonts/en/Inter-Black.ttf

    - family: InterExtraBold
      fonts:
        - asset: assets/fonts/en/Inter-ExtraBold.ttf

    - family: InterExtraLight
      fonts:
        - asset: assets/fonts/en/Inter-ExtraLight.ttf

    - family: InterLight
      fonts:
        - asset: assets/fonts/en/Inter-light.ttf

    - family: InterMedium
      fonts:
        - asset: assets/fonts/en/Inter-Medium.ttf

    - family: InterSemiBold
      fonts:
        - asset: assets/fonts/en/Inter-SemiBold.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/en/Inter-Regular.ttf

    - family: InterThin
      fonts:
        - asset: assets/fonts/en/Inter-Thin.ttf


